### ISSUE TITLE
plugin install INGRESS extension

### ISSUE THREAD

**Issue by styk-tv** [madcore-ai/cli#103]
Example component: flasker-hub

When we install plugin flasker-hub we specify app name that becomes subdomain for example:

plugin install flasker-hub --app_name=hubber

this brings up a service on the PRIVATE access (through follow me security group)

We now have extension (different route) through ingress server. All we need to do is run a single job to create another secure SSL route through Ingress server.

Jobname: madcore.plugin.ingress.add.service
Parameters
```
SERVICE_NAME - flasker-hub-service
SERVICE_PORT - 9019
SERVICE_NAMESPACE - flasker-hub-plugin
APP_NAME - hubber
```

This new job should be run at the end using --ingress optional parameter (we need to figure out where to take parameres from hubber is the app name will be same

resulting new service will be available all wide internet access through  https://hubber.ext.<team>.<domain.ext>

**Comment by hantden** [comment]
I think we need pass to plugin deploy job parameter like ingress=true/false and then add condition in deploy plugin job invoke or no job madcore.plugin.ingress.add.service

**Comment by styk-tv** [comment]
perfect, if we do that we can solve this without any CLI modification and using dynamic plugin parameters, we just need to make sure we can pass parameters to new job correctly.  app_name should be the same for public and private so that's no problem, what do you think about the other 3 @hantden ?

**Comment by hantden** [comment]
This parameter predefined in plugin kubernetes config file (yaml file). All this parameters present in service configuration file. We need just copy them to pligin.json file
SERVICE_NAME - flasker-hub-service
SERVICE_PORT - 9019
SERVICE_NAMESPACE - flasker-hub-plugin
