### ISSUE TITLE
configure set repos branch/commitid from command line

### ISSUE THREAD

**Issue by styk-tv** [madcore-ai/cli#110]
does not apply to cli (it should not reset itself) however controls set and propagation of branch/commitid throughout the build. this is extension of prod/dev environments and reset/force flags or can be used independently.

for now it would be good enough to be able to do this example:

```
madcore configure \
     --branch_core=issue-106-refactor-plugins \
     --commit_core=latest \
     --branch_plugins=development \
     --commit_plugins=709c49e09707aa5034242a2d21619165805f2c08 \
     --branch_cloudformation=master \
     --commit_cloudformation=0.5 \
     --branch_containers=master \
     --commit_containers=latest
```

commit param should also work with tags since they use same

```
git reset --hard tag-name

or

git reset --hard commit-id
```

if commit is set to reserved word "latest" then no reset is required. currently the CLI should automatically delete repo folders (similar to what we have in CI job) and not do PULL.  only way to ensure no conflicts and disconnected heads is to re-clone ALL repos on configure.

**Comment by botzill** [comment]
@styk-tv Can you explain what you mean by "does not apply to cli (it should not reset itself) " ? So, as I understand we need to be able to input commit/branch from the cmd line and we should not be asked about it during configure, right ? And basically all this params will be set to config for later use if any.

**Comment by styk-tv** [comment]
@botzill cli is built before configure happens in a separate build install process that's all i mean, so what is remaining is the other 4 repos listed in example.  

correct. we are not prompted for any of this if specified on command line. we want to be able to put this in CI or Bash script and be able to work out like that. perfect example is our CI server when we want to test a version (specific configuration of branches and commits) before we merge to development or master.

**Comment by botzill** [comment]
So, we should be able to set branch/commit only when we specify dev mode?

**Comment by styk-tv** [comment]
yes, default is always master or dev can be any

**Comment by styk-tv** [comment]
after merge to `development`

```
OSError: [Errno 2] No such file or directory: '/var/lib/jenkins/.madcore/plugins'
```

its possible plugins folder may not exist. you cannot assume its always there

**Comment by botzill** [comment]
Fixed: https://github.com/madcore-ai/cli/pull/114
