### ISSUE TITLE
stack create - is failing if roll back present

### ISSUE THREAD

**Issue by styk-tv** [madcore-ai/cli#14]
If previous stack create has rolled back then Stack is indeed created but it has been rolled back. Therefore stack resources are not present. 

We need to auto-remove rolled back stack and install again.

**Comment by styk-tv** [comment]
to confirm:

stack create should not remove rolled back in the same run. in a lot of case we can't see full error, we need to go to aws and see the error in details of events

stack create should remove rolled back stack upon new run.

**Comment by botzill** [comment]
Fixed.
