### ISSUE TITLE
dns delegation attempting for 1h

### ISSUE THREAD

**Issue by styk-tv** [madcore-ai/cli#25]
During Rebuild DNS delegation was attempting every second for 1h before final fail.

This should not be happening at all. No delegation is required since DNS stack is surviving destruction. We could easily verify with dig or other tool that dns to master subdomain is resolving to core.

In case of DNS DELEGATION for existing working delegation process should be replaced with Restore WITHOUT calling Let's Encrypt for certificate regeneration.

Described here:
https://github.com/madcore-ai/core/issues/17

**Comment by styk-tv** [comment]
#https://github.com/madcore-ai/core/issues/17

**Comment by botzill** [comment]
This was already implemented.
