### ISSUE TITLE
jenkins pipeline show progress of sub-jobs

### ISSUE THREAD

**Issue by styk-tv** [madcore-ai/cli#26]
As user executing from CLI i want to be able to see output of Pipeline sub-jobs

1) there might be a plugin that does that on jenkins level
2) if not a temporary switch to monitor a new job is required so figlet header and output can be displayed as part of displayed sequence. this will be required for ALL jobs executed from CLI

**Comment by botzill** [comment]
Could not find any plugin for it, I guess we will implement this.

**Comment by botzill** [comment]
Fixed.

**Comment by khazana95** [comment]
@botzill Is there a plugin for this now?
