### ISSUE TITLE
allow use of named profile of AWS cli

### ISSUE THREAD

**Issue by amkartashov** [madcore-ai/cli#37]
AWS CLI allows to use [named profiles](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-multiple-profiles) this will be handy if madcore cli would support it.

**Comment by botzill** [comment]
Yes, I guess that would be helpful as well. We can have multiple accounts setup locally and each of this accounts can have regions that are the same. So, I guess when we configure we need to scan ~/.aws and see the profiles and prompt user to select which one needs to be used. 

Let's see what @styk-tv say about this.
