### ISSUE TITLE
Check plugin installed properly

### ISSUE THREAD

**Issue by botzill** [madcore-ai/cli#43]
Currently if plugin is installed we change the client config and mark as installed. Next time this config is checked and if already installed skip it. We need to properly check the status with the madcore and see if it's up and installed without looking at local flag. 

Just a note: in case that you want to reinstall again you can use --force command:

``madcore plugin install slack --force`` - this will not check if already installed.

**Comment by styk-tv** [comment]
Linking those together. All will go into 0.6 #50 #43 #106
