### ISSUE TITLE
Validate index plugin json properly

### ISSUE THREAD

**Issue by botzill** [madcore-ai/cli#50]
Currently plugin index json file is growing a lots of things are added. We need to make a validator using http://docs.python-cerberus.org/en/stable/ so that we can run it every time run a cmd related to plugins and make sure we display a proper error that smth is wrong in json.

Also using this validation schema we may understand better how to add new plugin.

**Comment by styk-tv** [comment]
Linking those together. All will go into 0.6 #50 #43 #106
