### ISSUE TITLE
plugin remove k8s failing

### ISSUE THREAD

**Issue by styk-tv** [madcore-ai/cli#52]
- When running 'plugin remove k8s'  fail
- When running 'destroy' fail
- minor (no piglets)

**Comment by styk-tv** [comment]
- 'plugin remove' should in jenkins job clean after itself
- same with 'zero'
- same with 'contract'
- 'plugin status' should update real status based on detected information

![screen shot 2017-01-24 at 11 08 16](https://cloud.githubusercontent.com/assets/838921/22244949/79684bce-e225-11e6-9a94-8c6d891854fa.png)

**Comment by botzill** [comment]
what kind of failure, any message? Related to jobs that needs to clean after itself, this are jenkins jobs for plugin that needs to be updated and do the clean up work. I guess you can assign smth else for such tasks as it's related more to core jobs then to cli. 

Currently for k8s plugin it does this:

```
pipelineJob('madcore.plugin.k8s.delete') {
    definition {
	    cps {
            sandbox()
            script("""
            node {
                stage('K8S: delete') {
                }
                }
            """.stripIndent())
	    }
    }
}

```

Which os nothing, so it needs to be filled with proper delete cluster cleanup.

**Comment by styk-tv** [comment]
required for 0.4 completion

**Comment by botzill** [comment]
Please include fail messages, because for me it works ok k8s remove and destroy.
In general any issue should be included with full stack trace if any and proper logs messages.

**Comment by botzill** [comment]
Please also include what needs to be cleaned up? For k8s cluster seems there is nothing to clean up, node is removed from the cluster and that's all, no?

**Comment by botzill** [comment]
OK, about destroy - so, if we already have cluster plugins created, destroy should as well remove the CF for plugin cluster?

**Comment by botzill** [comment]
OK, now all this are fixed.
