### ISSUE TITLE
madcore status

### ISSUE THREAD

**Issue by styk-tv** [madcore-ai/cli#68]
new "status" command

endpoints - must be dynamic based on what is installed only

status - old idea of status header in cli that shows status of Core (online/offline) and FollowMe (Current/Outdated) + Detected Public IP - all of this in one line

repos  - table names + version local + version on core

**Comment by botzill** [comment]
So, currently we have `endpoints` cmd. Do we keep this command of replace with status?

Still is not clear for me how do we get the endpoints for specific plugin. There are plugins like: flasker which, as I understand, allow us to create any subdomain and deploy it. So how do we get all this subdomain that were dynamically created? 

The same applies to spark plugin. Currently when we deploy spark, by default,  it has 2 subdomain: spark and `zeppelin`. Plus `zeppelin` is smth that is hardcoded into crore itself. I think that we should have in plugin index also a list of endpoints definition(for extra if needed). If not, then we just check the default endpoint which is plugin name?

**Comment by styk-tv** [comment]
It's a problem that needs to be solved:

Static plugins will create single endpoint. That's easy.

Dynamic plugins like `spark submit` or `ingres add` must be satisfied and figured out at runtime.  Flasker is example of plugin that is static as example but the idea is to extend this be able to pass parameter of a docker image along with app_name to create new endpoint.

`deploy --ingress <app_name> <port> <hubrepo/hubcomponent> <component-args>`

**Comment by styk-tv** [comment]
some plugins may have multiple deployments, would be good if we can retrieve this through json post build on job endpoint in rest.

to be honest this is what habitat supervisor is supposed to do and we should start using it maybe the time has come where we cannot work without it anymore

**Comment by botzill** [comment]
@styk-tv Can you define the exact data/format that you want to see in header about status? 

As I understand it should be a line here:

```
Madcore Core CLI - Deep Learning & Machine Intelligence Infrastructure Controller
v0.4.2.21+gcbee8b7 Licensed under MIT (c) 2015-2017 Madcore Ltd - https://madcore.ai

<status_info>
```
?
About endpoints is still no clear for me how we can get the endpoints of a specific plugin, if it's dynamic one. We don't have any mapping related to plugin name - endpoint name? If we don't have then we can't figure out that. We need a consistent way to tell this and this should be the same for all plugins: static, dynamic.

**Comment by styk-tv** [comment]
This is how you retrieve from Jenkins (job should produce json fragments):
```
Uploading User Content

Jenkins has a mechanism called User Content, which allows arbitrary files to be served from http://yourhost/jenkins/userContent.

User content can be uploaded to Jenkins with the userContent DSL method.

userContent(String path, InputStream content)
In conjunction with streamFileFromWorkspace, any content can be upload from the seed job's workspace.

userContent('acme.png', streamFileFromWorkspace('images/acme.png'))
```

**Comment by styk-tv** [comment]
https://wiki.jenkins-ci.org/display/JENKINS/User+Content

**Comment by styk-tv** [comment]
https:// + endpoint = appname + (.ext.) + subdomain + domain. List of deployed apps is in Redis. Jobs should modify files so they can be used in Status. You should not build this information on client. Client should just display it.  Ext is added for endpoints published with --ingress flag or with plugin install-ext depends on how we solve this. (being built now)

**Comment by styk-tv** [comment]
we will sort this out properly, have to expose some services so ingress in 0.5 takes priority.
